### ISSUE TITLE
데이터 정리 open 

### ISSUE THREAD

**Issue by LSHReader** [makinarocks/awesome-industrial-machine-datasets#4]
### Tasks 

- [x] 데이터 정리 format을 참고할 만한 사이트 digging    
- [x] 데이터마다 label 추가 - simulation data 인지 or 아닌지   
- [x] 데이터 직접적으로 활용한 연구/논문 citation     
- [x] 데이터 출처 citation  

### Camera Ready     
- [x] 전체적인 feedback 과 검토  
- [x] repository title 정하기  
- [ ] 후임자 결정 (새로 추가되는 dataset에 대해 정리)      
- [ ]  README 홍보용으로 고치기   
- [ ] facebook community - 한국어/영어로 둘 다 홍보    
- [ ] repository public화       
- [ ] To do list 지속적 업데이트  

### To do list  
- [ ]  PHM data challenge 역대 데이터 수집 후 정리
